[build]
  functions = "functions"

[functions]
  directory = "functions/"
  external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
